version: '3.5'

services:
  postgres:
    container_name: trabalho-dev-web
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-teste}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-teste}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:

